INFO	2024-04-17 17:42:23,681	[loggers.py:32]	测试日志
INFO	2024-04-17 17:44:15,579	[loggers.py:32]	测试日志
INFO	2024-04-17 17:44:36,932	[loggers.py:32]	测试日志
INFO	2024-04-17 17:49:49,314	[loggers.py:40]	测试日志
WARNING	2024-04-18 15:01:33,772	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002332DEA2DB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e22e26323016deea95fdeb2175e3a923/window/maximize
WARNING	2024-04-18 15:01:37,847	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002332DED80B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e22e26323016deea95fdeb2175e3a923/window/maximize
WARNING	2024-04-18 15:01:41,924	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002332DED82F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e22e26323016deea95fdeb2175e3a923/window/maximize
WARNING	2024-04-18 15:01:50,269	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002332DEDAB40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e22e26323016deea95fdeb2175e3a923/window/maximize
WARNING	2024-04-18 15:01:54,317	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002332DED9D60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e22e26323016deea95fdeb2175e3a923/window/maximize
WARNING	2024-04-18 15:01:58,404	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002332DEDA060>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e22e26323016deea95fdeb2175e3a923/window/maximize
WARNING	2024-04-18 15:03:00,030	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000272325A3080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3c0f0ac1cd6a1c537971cc772f106cc1/window/maximize
WARNING	2024-04-18 15:03:04,116	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000272325A3E30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3c0f0ac1cd6a1c537971cc772f106cc1/window/maximize
WARNING	2024-04-18 15:03:08,207	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000272325F4080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3c0f0ac1cd6a1c537971cc772f106cc1/window/maximize
WARNING	2024-04-18 15:06:18,936	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C614DEE870>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/266593c5614e222d764ce978336afeb6/window/maximize
WARNING	2024-04-18 15:06:23,043	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C614DEF8F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/266593c5614e222d764ce978336afeb6/window/maximize
WARNING	2024-04-18 15:06:27,152	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C614E10140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/266593c5614e222d764ce978336afeb6/window/maximize
WARNING	2024-04-18 15:07:04,444	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29CAA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/source
WARNING	2024-04-18 15:07:08,531	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29CE60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/source
WARNING	2024-04-18 15:07:12,632	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29D010>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/source
WARNING	2024-04-18 15:07:20,849	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29CAD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/url
WARNING	2024-04-18 15:07:24,945	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29DFD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/url
WARNING	2024-04-18 15:07:29,041	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29E180>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/url
WARNING	2024-04-18 15:07:37,248	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29E4E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/window
WARNING	2024-04-18 15:07:41,349	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29E660>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/window
WARNING	2024-04-18 15:07:45,460	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29E810>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/window
WARNING	2024-04-18 15:07:53,649	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29E300>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/se/log/types
WARNING	2024-04-18 15:07:57,739	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29E360>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/se/log/types
WARNING	2024-04-18 15:08:01,823	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29EC90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/se/log/types
WARNING	2024-04-18 15:08:10,011	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29F080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/orientation
WARNING	2024-04-18 15:08:14,112	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29F1A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/orientation
WARNING	2024-04-18 15:08:18,205	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77F29F350>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c29345311b039ff014e8f7966481b6c4/orientation
WARNING	2024-04-18 15:08:44,698	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D4650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:08:48,777	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD3074350>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:08:52,861	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D4C80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:09:15,564	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D4200>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:09:19,654	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D4EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:09:23,749	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D5B50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:10:29,257	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D6930>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/window/maximize
WARNING	2024-04-18 15:10:33,359	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D6B70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/window/maximize
WARNING	2024-04-18 15:10:37,446	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D6DB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/window/maximize
WARNING	2024-04-18 15:10:45,724	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D6750>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:10:49,799	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D4E60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:10:53,875	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFD31D7590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8c7bf89bd6965f2e69e13732c2d2df4a/source
WARNING	2024-04-18 15:12:59,123	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253D3483D70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/549f627b0e28b4ac22c381af742ec8f4/window/maximize
WARNING	2024-04-18 15:13:03,199	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253D3483D10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/549f627b0e28b4ac22c381af742ec8f4/window/maximize
WARNING	2024-04-18 15:13:07,273	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253D3483FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/549f627b0e28b4ac22c381af742ec8f4/window/maximize
WARNING	2024-04-18 15:14:21,315	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FBF8ACE7E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b987dda6ef9f09a71e77c2f4fb8acb24/window/maximize
WARNING	2024-04-18 15:14:25,396	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FBF8ACE9C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b987dda6ef9f09a71e77c2f4fb8acb24/window/maximize
WARNING	2024-04-18 15:14:29,496	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FBFAF62FF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b987dda6ef9f09a71e77c2f4fb8acb24/window/maximize
WARNING	2024-04-18 15:15:24,986	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A410E02A20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/88a417098347774e44da4a7af9157529/window/maximize
WARNING	2024-04-18 15:15:29,058	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A410E02ED0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/88a417098347774e44da4a7af9157529/window/maximize
WARNING	2024-04-18 15:15:33,149	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A410E03F20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/88a417098347774e44da4a7af9157529/window/maximize
WARNING	2024-04-18 15:17:06,118	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002450C2B3050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/2e8b6b7bc1e0431121f8cd0b92ac7732/window/maximize
WARNING	2024-04-18 15:17:10,197	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002450C2B3110>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/2e8b6b7bc1e0431121f8cd0b92ac7732/window/maximize
WARNING	2024-04-18 15:17:14,243	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002450C304140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/2e8b6b7bc1e0431121f8cd0b92ac7732/window/maximize
WARNING	2024-04-18 15:19:09,802	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000231AC073350>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1bc0bcc636339714eb7afded9514f1df/window/maximize
WARNING	2024-04-18 15:19:13,857	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000231A9BF42C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1bc0bcc636339714eb7afded9514f1df/window/maximize
WARNING	2024-04-18 15:19:17,954	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000231AC0A81D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1bc0bcc636339714eb7afded9514f1df/window/maximize
WARNING	2024-04-18 15:20:13,553	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A7DA63290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/964a4f5601f53a607380518aaf1e2d47/window/maximize
WARNING	2024-04-18 15:20:17,641	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A7DA63410>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/964a4f5601f53a607380518aaf1e2d47/window/maximize
WARNING	2024-04-18 15:20:21,703	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015A7DA983B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/964a4f5601f53a607380518aaf1e2d47/window/maximize
WARNING	2024-04-18 15:24:46,210	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E8013B440>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/47ee890213da026ced765e5e33b9420a/window/maximize
WARNING	2024-04-18 15:24:50,281	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020EFFD652B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/47ee890213da026ced765e5e33b9420a/window/maximize
WARNING	2024-04-18 15:24:54,382	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E8017C2C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/47ee890213da026ced765e5e33b9420a/window/maximize
WARNING	2024-04-18 15:26:01,004	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002066D40C9B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d1440279e702c06038bf422c70a353cc/timeouts
WARNING	2024-04-18 15:26:05,111	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002066D40CAD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d1440279e702c06038bf422c70a353cc/timeouts
WARNING	2024-04-18 15:26:09,198	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002066D40CC80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d1440279e702c06038bf422c70a353cc/timeouts
WARNING	2024-04-18 15:26:52,739	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020CBC850EC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1d203b211c7901148f77532ba4958c1e/timeouts
WARNING	2024-04-18 15:26:56,815	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020CBC851700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1d203b211c7901148f77532ba4958c1e/timeouts
WARNING	2024-04-18 15:27:00,920	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020CBCBD74A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1d203b211c7901148f77532ba4958c1e/timeouts
WARNING	2024-04-18 15:27:29,526	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C4D30225A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ba24aa9a04d61e49710efc2e3cd4b921/url
WARNING	2024-04-18 15:27:33,623	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C4D3112930>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ba24aa9a04d61e49710efc2e3cd4b921/url
WARNING	2024-04-18 15:27:37,721	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C4D3113DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ba24aa9a04d61e49710efc2e3cd4b921/url
WARNING	2024-04-18 15:32:34,772	[connectionpool.py:874]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A095864F80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e1c9469e08c186fe0100fb61491f0051/url
WARNING	2024-04-18 15:32:38,869	[connectionpool.py:874]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A095864620>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e1c9469e08c186fe0100fb61491f0051/url
WARNING	2024-04-18 15:32:42,963	[connectionpool.py:874]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A0958651C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e1c9469e08c186fe0100fb61491f0051/url
WARNING	2024-04-23 19:23:44,607	[selenium_manager.py:149]	The chromedriver version (123.0.6312.105) detected in PATH at D:\dev\python\python3.12.2\chromedriver.exe might not be compatible with the detected chrome version (124.0.6367.61); currently, chromedriver 124.0.6367.60 is recommended for chrome 124.*, so it is advised to delete the driver in PATH and retry
WARNING	2024-04-26 16:19:39,976	[selenium_manager.py:149]	The chromedriver version (123.0.6312.105) detected in PATH at D:\dev\python\python3.12.2\chromedriver.exe might not be compatible with the detected chrome version (124.0.6367.62); currently, chromedriver 124.0.6367.91 is recommended for chrome 124.*, so it is advised to delete the driver in PATH and retry
